### PR TITLE
Support for Fedora native packages

### PR DESCRIPTION
**Pull request by davidkostal**

### CODE REVIEW

**Comment by skpy** [comment]
Thanks @davidkostal !  I've been delaying merging this while I try to get some rspec tests for this module.  It seems I've run into [this bug](https://github.com/rodjek/rspec-puppet/pull/237) with rspec-puppet. I may be able to move forward with the tests, and just deal with failures that result from that bug.

**Comment by skpy** [comment]
@davidkostal thanks for your patience, and sorry it's taken so long to get back to you!  I've merged my tests branch, and would like to merge this PR.  Can I ask you to update this with the appropriate tests?

I  took a stab at updating [yum_repo_spec.rb](https://gist.github.com/skpy/745767fa0c33c950ab16) to do some minimal validation.

Thanks!

**Comment by daenney** [comment]
@skpy @davidkostal any progress on this? This has been hanging for over half a year so I'm inclined to close it for now.

**Comment by skpy** [comment]
I dropped the ball, and never tested this.  I'm okay closing it until someone is willing to shepherd Fedora fully.

**Pull request closed without merging**
